title: project
icon: ®

status:
  draft: true
  listed: true

options:
  url: false
  delete: false

columns:
  - width: 1/2
        sections:
            content:
                type: fields
                fields:
                    type:
                        label: Type
                        type: radio
                        options:
                            seminar: Seminar
                            free: Free Project
                            prediploma: Prediploma
                            diploma: Diploma
                    medium:
                        label: Medium
                        type: checkboxes
                        options:
                            book: Book
                            poster: Poster
                            type: Typeface
                            web: Website
                            video: Video
                            textile: Textile
                            illu: Illustration
                            sound: Sound
                            space: Space
                            exhibition: Exhibition
                            event: Events
            gallery:
                headline: Gallery
                type: files
                layout: list
                template: image
                back: white
            videos:
                headline: Gallery
                type: files
                layout: list
                template: video
                back: white
 
  - width: 1/2
    fields:
      supervisor(s):
        type: structure
        fields:
            supervisor:
                label: Supervisor
                placeholder: Dr. Super Visor
                type: select
                options: query
                query: site.children.children.template("person")
      author(s):
        type: structure
        fields:
            author:
                label: Author
                placeholder: Stud Ent
                type: select
                options: query
                query: site.children.children.template("person")
      semester:
        label: Semester
        type: select
        options:
            WS: WS 2010
            SS: SS 2010
      about:
        label: About
        type: textarea
      task:
        label: Was there a Task?
        type: textarea
      link:
        label: Link
        type: structure
        fields:
          platform:
            label: Website name
            type: text
            width: 1/2
          url:
            label: URL
            type: url
            width: 1/2
